version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev